#pragma once
#define LV_CONF_H
#define LV_COLOR_DEPTH 32
#define LV_COLOR_16_SWAP 0
#define LV_USE_ARC 1
#define LV_USE_LABEL 1
#define LV_USE_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_USE_DRAW_SW 1
#define LV_DRAW_SW_COMPLEX 1
#define LV_USE_LOG 0
#define LV_USE_OS LV_OS_NONE
#define LV_DEF_REFR_PERIOD 16
#define LV_BUILD_DEMOS 0
#define LV_BUILD_EXAMPLES 0
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
